GET http://localhost:8080/
###

GET http://localhost:8080/admin-jwks.json

###
GET http://localhost:8080/api/login

###
POST http://localhost:8080/api/login
Content-Type: application/json

{"username":"customer","password":"strong@password"}

###
GET http://localhost:8080/api/debug
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImN1c3RvbWVyLWtleSJ9.eyJyb2xlIjoidXNlciIsInN1YiI6ImN1c3RvbWVyIiwiaXNzIjoiY3VzdG9tZXItaXNzdWVyIiwiYXVkIjoicXVpbGwtY3VzdG9tZXIiLCJpYXQiOjE3NjI2ODk5OTksImV4cCI6MTc2MjY5MzU5OX0.Hs7xYmbJlMGo-lwtPnOFDVq4apPT2kI0vqQ5uMBIIMM1-UGnS3bTiiVKmO7mMbVelMac5oXvt_2VGnM5CPgWNL7ICQaKVBXnjux30tHiAF5nHZ2cBGUGGG-PTKoZlGAns5BeGX5QPdiOXvgZ6Agyfpz1RCnaOFglOERR_UuQPzY-66IXADdhoMtZ7x_1-1a4elAhwJraBG1OutZbQ686_wyeog_Xuj3F5VSD9HMyKO-ER69IvlN_772p3dxpoS9YJQUw-ILHzmx4WTesYtuZVjC8foUV2A9VPQPKDlvYUy4dsSpN0WPPgyMw94aILfhhX1VgRMQMkeynv77fHVUsWg

###
GET http://localhost:8080/api/profile
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImN1c3RvbWVyLWtleSJ9.eyJyb2xlIjoidXNlciIsInN1YiI6ImN1c3RvbWVyIiwiaXNzIjoiY3VzdG9tZXItaXNzdWVyIiwiYXVkIjoicXVpbGwtY3VzdG9tZXIiLCJpYXQiOjE3NjI1NjI3MDAsImV4cCI6MTc2MjU2NjMwMH0.OtVSj8Kcpg06vkdFuZVAZrK0IVYwwXJFzFzIvqBnoPAyE6Nkms6nHIib2t5fpVWHD5ZjE_wMi2qzS8fXnBWIKING5vhRYXTrRUHxSzAfzTaNa1fcj2skG757mAQDznjGtzNqWtTwaoZZVz6fmJqIUhW925I4-zRQ5JBPWG_oHpVBNJq8sy8kHFxvx2IsDTD3belAkfVfrhcQ3nM11bnMSI-xv071XX4e6Fcwy26q7aMM19NiYfWTbnLwRAXeZbgbPfN6Mfx9UbOfcCv5P2jyAnS6mQC10cckL3e4E4CStcSrHf-o936JAr7KWomHe6uklZbVmXNplsZcpXwgvPZrag

###
POST /api/debug/jwks-test HTTP/1.1
Host: 192.168.64.1:8080
Content-Type: application/json
Content-Length: 650

{
  "issuer": "noisy_echidna",
  "jwks_url": "http://192.168.64.2:8000/jwks.json",
  "token": "eyJhbGciOiJSUzI1NiIsImtpZCI6ImF0dGFja2VyLWtleSJ9.eyJyb2xlIjoiYWRtaW4iLCJzdWIiOiJlY2hpZG5hLWFkbWluIiwiaXNzIjoibm9pc3lfZWNoaWRuYSIsImF1ZCI6InF1aWxsLWFkbWluIiwiaWF0IjoxNzYyNjYzMzE0LCJleHAiOjE3NjI2NjQyMTR9.IxTJHwYhlQj7shaYGNWZlrVcgU2jMLjvu8sZznPS3axy5Qoku-KtFSUoHE4bhRaGvmyaMzS0CoWoKgigCa-5GDJu4BZF7KkFMxyPTIX7Q6aa-kq7vGzZqiqx2qveX8rhqUE-jWWZtf33rz9iEFVTQVrdFVndR-k86LsTQ5DCE6-O3bXl08NhRv63v5x4q88NR_bIfm7eQKJxCBwc6e9WGXW-UI05zGo78gh42H16kwl__uxze29Auho6U6Vm0s2fOv_wwSD2GCPQEYZDSNEaJ2CpFmriZkxN7Y_tUW4L0CGWKijULhjeogFD4GoL7T-guDBX9QvKD4ts2rbPSOcyGw"
}

###
GET /api/admin HTTP/1.1
Host: 192.168.64.1:8080
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImF0dGFja2VyLWtleSJ9.eyJyb2xlIjoiYWRtaW4iLCJzdWIiOiJlY2hpZG5hLWFkbWluIiwiaXNzIjoibm9pc3lfZWNoaWRuYSIsImF1ZCI6InF1aWxsLWFkbWluIiwiaWF0IjoxNzYyNjY3ODU0LCJleHAiOjE3NjI2Njg3NTR9.t0V6ZmL30PcGhzDUh6oDvvBM2uPU97jflqv1HVAu69SWOPV7kxT_iqomeEuH6-iaVqJ5ETL9XnrAv9RCxYtVT7AVYzLe3HOolj3iB7uRL5QZV2HUGdqCKdft_3pm6-c5i7xZYY11JCO8o6Prpm1UhTbSARJ1mR6yuq4wRte_V7lSO8OwTNr-TCUIo0I5rnzaHuxz90uXddSGqIkUiq_K4a3TZJK8GA5ojf8fP2oW6ITXPMUj9GvEgr6NmF4v7AKrsXJiSvViMzfPVNaOAGKHEnnYbEmM9fTA_UZRgwm3DiC3ZsHKj3mH1pFHsVGBOFQUKtbq2jEtSwa8nNY8zLGbpQ